spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/jwt_security
    username: username
    password: password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/jwt_security
    schemas: public
    user: username
    password: password
    driverClassName: org.postgresql.Driver
#    outOfOrder: true
    baselineOnMigrate: true
    locations: classpath:db/migration
#    ignoreMigrationPatterns: '*:ignored'

#springdoc.api-docs.path: /api-docs
#springdoc.api-docs.enabled: true
#springdoc.swagger-ui.enabled: true

dirLog: /data/logs/spring-reactive

logging:
  path: ${dirLog}
  file.name: ${dirLog}/reactive.log
  #  file.clean-history-on-start: true
  pattern.rolling-file-name: ${dirLog}/%d{yyyyMMdd}/reactive.%d{yyyyMMdd}.%i.log.gz
  pattern.console: "%M - %msg%n"
  pattern.file: "%msg%n"
  #  pattern.console: "%d{yyyy-MM-dd HH:mm:ss} | [%thread] | %-5level | %logger{36}.%M - %msg%n"
  #  pattern.file: "%d{yyyy-MM-dd HH:mm:ss} | [%thread] | %-5level | %logger{36}.%M - %msg%n"
  file.max-size: 100MB
  #  file.total-size-cap: 2MB
  file.max-history: 15
  level:
    #    web: TRACE
    com.saravan: debug
    #    org.hibernate.SQL: debug
    org.springframework.web: debug
    org.springframework.web.servlet.resource: WARN
    # org.springframework: trace
    #org.hibernate.type: trace
    root: info
